version: '3.9'
services:
  postgres-database:
    container_name: postgres-database
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - "32769:5432"
    volumes:
      - ./src/data/postgres:/var/lib/postgresql/data
      - ./src/data/patient.sql:/docker-entrypoint-initdb.d/patient.sql
  nativapp:
    container_name: prueba-nativapp
    build: .
    restart: always
    env_file: 
      - .env
    ports: 
      - "3000:9000"
