version: '3.9'
services:
  postgres-database:
    container_name: postgres-database
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - "32769:5432"
  nativapp:
    container_name: prueba-nativapp
    build: .
    restart: always
    env_file: 
      - .env
    ports: 
      - "3000:9000"
